travis:
  secure:
    BINSTAR_TOKEN: cpczDR0XuK3lhFut/WznI0ie/v6pnV/vNubXoNgcZH8BxoDn187eMxjkTTcN2jRXzDGc8B0Ykm6nYYdbL0pZ/SXnxw/SGcNeI4Ybe8cOJ83CgzHqR8HXay0nQ+czjlonsNCpLLbiMjaDokTbnWRTtDkNaTRR0ULGY6iQRZVX/yHiYdadQC4rinVCvidgoYBGHCqZIrMt6b/Fl5rwdmrTgpsMCRE13h6r0Arqf66OTVKc8+Eo2Km0GpSJaitsMGGC8RM6ILLAccStWJVEG0epgbSpCuj44c7W+QwhwO2SbBS3NNpo4VgLXeMEgoal2MTfXAaDOzGKbHaxNGJrRtaFKIXJW/2ly1JYJL9kJkMNrBEJVbnfTazpterKCYVAMfHfrnkUzWqNRzWNuN74v2+bV5YOQgj94SrLJzgNI4LeDs63+W3PH9Y4D7vz7g4M2qWAFqw0tM7MGsrTPCHgFlM/q0LHHbptzdwx/KNrEdXqFzBfViCgdATEFB/hQyPloJeOPYC7PR8mjCaGDatEqIwAL3dY3xS5YCqkkmVmqamuHxX5/WPYM3d3Re25wkCvT9ooygvuRk+WiOKNePJ9KXWF6OmBPIUygCFFjWrKoDWtitThG0IQXbWvA2yLCyiZevBMYse2JYwHU0X2fsiNiiBWUeDXMPc4t1ueD1HQ5mU4m2I=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
